import type { CSSProperties } from 'react'

const PIXEL_FONT = "'Galmuri11', 'Courier New', monospace"

export const authStyles: Record<string, CSSProperties> = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
  },
  card: {
    position: 'absolute',
    top: '52%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 380,
    maxWidth: 'calc(100vw - 32px)',
    padding: '24px 22px 20px',
    background: 'rgba(252, 247, 235, 0.45)',
    backdropFilter: 'blur(4px)',
    border: '2px solid rgba(58, 36, 16, 0.7)',
    borderRadius: 10,
    boxShadow: 'none',
    color: '#3a2410',
    fontFamily: PIXEL_FONT,
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 10,
    background: 'transparent',
    border: 'none',
    fontSize: 18,
    lineHeight: 1,
    color: '#5a3818',
    cursor: 'pointer',
    padding: 4,
    fontFamily: PIXEL_FONT,
  },
  title: {
    margin: '0 0 16px',
    fontSize: 22,
    fontWeight: 400,
    textAlign: 'center',
    color: '#3a2410',
    letterSpacing: '0.08em',
    fontFamily: PIXEL_FONT,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 14,
    color: '#5a3818',
    fontFamily: PIXEL_FONT,
  },
  input: {
    padding: '10px 12px',
    fontSize: 14,
    background: '#fbf3df',
    border: '2px solid #3a2410',
    borderRadius: 6,
    color: '#3a2410',
    outline: 'none',
    fontFamily: PIXEL_FONT,
  },
  error: {
    color: '#a02020',
    fontSize: 13,
    fontFamily: PIXEL_FONT,
  },
  errorBox: {
    padding: 10,
    background: '#f6d6c8',
    color: '#7a1818',
    border: '2px solid #c25a17',
    borderRadius: 6,
    fontSize: 13,
    fontFamily: PIXEL_FONT,
  },
  primaryButton: {
    marginTop: 6,
    padding: '12px 16px',
    fontSize: 16,
    fontWeight: 400,
    color: '#fff5d8',
    background: '#e8782a',
    border: '2px solid #3a2410',
    borderRadius: 6,
    cursor: 'pointer',
    fontFamily: PIXEL_FONT,
    letterSpacing: '0.06em',
  },
}
