LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"
LEFT_ELBOW = "LEFT_ELBOW"
RIGHT_ELBOW = "RIGHT_ELBOW"
LEFT_WRIST = "LEFT_WRIST"
RIGHT_WRIST = "RIGHT_WRIST"
LEFT_KNEE = "LEFT_KNEE"
RIGHT_KNEE = "RIGHT_KNEE"
LEFT_ANKLE = "LEFT_ANKLE"
RIGHT_ANKLE = "RIGHT_ANKLE"

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)
REQUIRED_TAEKWONDO_TRACKING_POINTS = (
    LEFT_SHOULDER,
    RIGHT_SHOULDER,
    LEFT_ELBOW,
    RIGHT_ELBOW,
    LEFT_WRIST,
    RIGHT_WRIST,
    LEFT_HIP,
    RIGHT_HIP,
    LEFT_KNEE,
    RIGHT_KNEE,
    LEFT_ANKLE,
    RIGHT_ANKLE,
)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
MIN_SAFE_SCALE_REFERENCE = 0.01
TRACKING_LOST_THRESHOLD = 0.5
TRACKING_CONFIDENCE_GOOD = 0.9
DEFAULT_CALIBRATION_TARGET_FRAMES = 5
MAX_CALIBRATION_TARGET_FRAMES = 100

ACTION_READY = "ready"
ACTION_LOW_BLOCK = "low_block"
ACTION_MIDDLE_PUNCH = "middle_punch"
ACTION_UNCLASSIFIED = "unclassified"
STANCE_READY = "ready_stance"
STANCE_WALKING = "walking_stance"
STANCE_FRONT = "front_stance"

ACTION_LABELS = (
    ACTION_READY,
    ACTION_LOW_BLOCK,
    ACTION_MIDDLE_PUNCH,
)

STANCE_LABELS = (
    STANCE_READY,
    STANCE_WALKING,
    STANCE_FRONT,
)

DIRECTION_FRONT = "front"
DIRECTION_LEFT = "left"
DIRECTION_RIGHT = "right"
DIRECTION_UNCLASSIFIED = "unclassified"

DIRECTION_LABELS = (
    DIRECTION_FRONT,
    DIRECTION_LEFT,
    DIRECTION_RIGHT,
)

TURN_NONE = "no_turn"
TURN_LEFT = "turn_left"
TURN_RIGHT = "turn_right"

MIN_CLASSIFICATION_CONFIDENCE = 0.45

FEATURE_WRIST_NEAR_HIP_DISTANCE_MAX = 0.45
FEATURE_DOMINANT_ACTION_MIN_SCORE = 0.8
FEATURE_DOMINANT_ACTION_MARGIN = 0.15

READY_HANDS_BALANCED_Y_DIFF_MAX = 0.25
READY_HANDS_NOT_EXTENDED_X_MAX = 0.45
READY_BOTH_NEAR_HIPS_WEIGHT = 0.4
READY_HANDS_BALANCED_WEIGHT = 0.25
READY_HANDS_NOT_EXTENDED_WEIGHT = 0.2
READY_ELBOWS_NOT_LOCKED_WEIGHT = 0.15

LOW_BLOCK_WRIST_Y_MIN = 0.25
LOW_BLOCK_FAR_FROM_CENTER_REFERENCE = 1.2
LOW_BLOCK_WRIST_LOW_WEIGHT = 0.35
LOW_BLOCK_FAR_FROM_CENTER_WEIGHT = 0.25
LOW_BLOCK_EXTENDED_ARM_WEIGHT = 0.25
LOW_BLOCK_OPPOSITE_NEAR_HIP_WEIGHT = 0.15

MIDDLE_PUNCH_WRIST_Y_MIN = -0.9
MIDDLE_PUNCH_WRIST_Y_MAX = -0.1
MIDDLE_PUNCH_FAR_FROM_CENTER_REFERENCE = 1.2
MIDDLE_PUNCH_TORSO_HEIGHT_WEIGHT = 0.35
MIDDLE_PUNCH_FAR_FROM_CENTER_WEIGHT = 0.25
MIDDLE_PUNCH_EXTENDED_ARM_WEIGHT = 0.25
MIDDLE_PUNCH_OPPOSITE_NEAR_HIP_WEIGHT = 0.15

ELBOW_EXTENDED_THRESHOLD = 150.0
ELBOW_SEMI_EXTENDED_THRESHOLD = 120.0
ELBOW_BENT_MIN = 60.0
ELBOW_BENT_MAX = 150.0
ELBOW_SLIGHTLY_BENT_MAX = 165.0

MIN_STANCE_CLASSIFICATION_CONFIDENCE = 0.45

STANCE_HIP_WIDTH_MIN = 0.1
STANCE_READY_WIDTH_RATIO_MAX = 1.6
STANCE_WALKING_WIDTH_RATIO_MIN = 1.8
STANCE_WALKING_WIDTH_RATIO_MAX = 3.6
STANCE_FRONT_WIDTH_RATIO_MIN = 2.5
STANCE_FRONT_WIDTH_RATIO_REFERENCE = 4.5
STANCE_KNEE_STRAIGHT_THRESHOLD = 155.0
STANCE_KNEE_SOFT_STRAIGHT_THRESHOLD = 145.0
STANCE_KNEE_BENT_THRESHOLD = 145.0
STANCE_KNEE_DEEP_BENT_THRESHOLD = 130.0
STANCE_BEND_SIDE_MARGIN = 8.0

STANCE_READY_WIDTH_WEIGHT = 0.5
STANCE_READY_KNEES_WEIGHT = 0.5

STANCE_WALKING_WIDTH_WEIGHT = 0.45
STANCE_WALKING_KNEES_WEIGHT = 0.35
STANCE_WALKING_BALANCE_WEIGHT = 0.2

STANCE_FRONT_WIDTH_WEIGHT = 0.3
STANCE_FRONT_BENT_KNEE_WEIGHT = 0.35
STANCE_FRONT_STRAIGHT_KNEE_WEIGHT = 0.2
STANCE_FRONT_ASYMMETRY_WEIGHT = 0.15

MIN_DIRECTION_CLASSIFICATION_CONFIDENCE = 0.45
DIRECTION_FRONT_SHOULDER_BALANCE_MAX = 0.2
DIRECTION_FRONT_ANKLE_BALANCE_MAX = 0.35
DIRECTION_FRONT_EXTENT_DIFF_MAX = 0.5
DIRECTION_SIDE_EXTENT_DIFF_REFERENCE = 0.5
DIRECTION_SIDE_ANKLE_MARGIN = 0.2

DIRECTION_FRONT_SHOULDER_WEIGHT = 0.4
DIRECTION_FRONT_ANKLE_WEIGHT = 0.4
DIRECTION_FRONT_EXTENT_WEIGHT = 0.2
DIRECTION_SIDE_EXTENT_WEIGHT = 0.7
DIRECTION_SIDE_ANKLE_WEIGHT = 0.3
