LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"
LEFT_KNEE = "LEFT_KNEE"
RIGHT_KNEE = "RIGHT_KNEE"
LEFT_ANKLE = "LEFT_ANKLE"
RIGHT_ANKLE = "RIGHT_ANKLE"
LEFT_ELBOW = "LEFT_ELBOW"
RIGHT_ELBOW = "RIGHT_ELBOW"
LEFT_WRIST = "LEFT_WRIST"
RIGHT_WRIST = "RIGHT_WRIST"

MOTION_REPLAY_LANDMARK_NAMES = (
    LEFT_SHOULDER,
    RIGHT_SHOULDER,
    LEFT_ELBOW,
    RIGHT_ELBOW,
    LEFT_WRIST,
    RIGHT_WRIST,
    LEFT_HIP,
    RIGHT_HIP,
    LEFT_KNEE,
    RIGHT_KNEE,
    LEFT_ANKLE,
    RIGHT_ANKLE,
)

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)
REQUIRED_MARCH_TRACKING_POINTS = (LEFT_KNEE, RIGHT_KNEE, LEFT_ANKLE, RIGHT_ANKLE)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
NUMERIC_EPSILON = MIN_SCALE_REFERENCE

DEFAULT_MARCH_TARGET_STEPS = 8

DEFAULT_MARCH_THIGH_ANGLE_THRESHOLD = 25.0

DEFAULT_MARCH_DOMINANCE_MARGIN = 3.0

DEFAULT_MARCH_RELEASE_THRESHOLD = 25.0

DEFAULT_MARCH_TORSO_TILT_MAX = 12.0

DEFAULT_MARCH_PELVIS_SHIFT_MAX = 0.30

DEFAULT_MARCH_DEPTH_SHIFT_MAX = 0.40

DEFAULT_FEEDBACK_STREAK_THRESHOLD = 8
DEFAULT_FEEDBACK_DISPLAY_FRAMES = 60
DEFAULT_FEEDBACK_CLEAR_FRAMES = 5
DEFAULT_GYMNASTICS_BASELINE_TARGET_FRAMES = 3
DEFAULT_DANIEL_FEEDBACK_STREAK_THRESHOLD = 2
DEFAULT_DANIEL_FEEDBACK_DISPLAY_FRAMES = 24
DEFAULT_DANIEL_FEEDBACK_CLEAR_FRAMES = 1
DEFAULT_STRETCH_HOLD_TARGET_MS = 10_000
DEFAULT_HOLD_MAX_FRAME_GAP_MS = 250
DANIEL_FORWARD_PRESS_MOTION_NAME = "\uc190 \uae4d\uc9c0 \ub07c\uace0 \uc55e\uc73c\ub85c \ubc00\uae30"
DANIEL_UPWARD_PRESS_MOTION_NAME = "\uc190 \uae4d\uc9c0 \ub07c\uace0 \uc704\ub85c \ubc00\uae30"
DANIEL_LEFT_SIDE_BEND_MOTION_NAME = "\uc67c\ucabd \uc606\uad6c\ub9ac \uad7d\ud788\uae30"
DANIEL_RIGHT_SIDE_BEND_MOTION_NAME = "\uc624\ub978\ucabd \uc606\uad6c\ub9ac \uad7d\ud788\uae30"
DANIEL_FORWARD_BEND_MOTION_NAME = "\uc190 \uae4d\uc9c0 \ub07c\uace0 \uc544\ub798\ub85c \uc219\uc774\uae30"

DEFAULT_DANIEL_FORWARD_PRESS_FORWARD_THRESHOLD = 0.06
DEFAULT_DANIEL_FORWARD_PRESS_WRIST_EXTENSION_THRESHOLD = 0.05
DEFAULT_DANIEL_FORWARD_PRESS_WRIST_GAP_MAX = 0.65
DEFAULT_DANIEL_FORWARD_PRESS_HEIGHT_ERROR_MAX = 0.55
DEFAULT_DANIEL_FORWARD_PRESS_WRIST_BELOW_SHOULDER_MIN = 0.02
DEFAULT_DANIEL_FORWARD_PRESS_ARM_STRAIGHT_THRESHOLD = 120.0
DEFAULT_DANIEL_FORWARD_PRESS_TORSO_TILT_MAX = 14.0
DEFAULT_DANIEL_UPWARD_PRESS_HEIGHT_THRESHOLD = 0.50
DEFAULT_DANIEL_UPWARD_PRESS_HEIGHT_BALANCE_THRESHOLD = 0.18
DEFAULT_DANIEL_UPWARD_PRESS_ARM_STRAIGHT_THRESHOLD = 145.0
DEFAULT_DANIEL_UPWARD_PRESS_TORSO_TILT_MAX = 14.0
DEFAULT_DANIEL_LEFT_SIDE_BEND_TILT_THRESHOLD = 0.18
DEFAULT_DANIEL_LEFT_SIDE_BEND_WRIST_HEIGHT_THRESHOLD = 0.40
DEFAULT_DANIEL_LEFT_SIDE_BEND_ARM_STRAIGHT_THRESHOLD = 145.0
DEFAULT_DANIEL_RIGHT_SIDE_BEND_TILT_THRESHOLD = 0.18
DEFAULT_DANIEL_RIGHT_SIDE_BEND_WRIST_HEIGHT_THRESHOLD = 0.40
DEFAULT_DANIEL_RIGHT_SIDE_BEND_ARM_STRAIGHT_THRESHOLD = 145.0
DEFAULT_DANIEL_FORWARD_BEND_ANGLE_THRESHOLD = 55.0
DEFAULT_DANIEL_FORWARD_BEND_WRIST_DROP_THRESHOLD = 1.10
DEFAULT_DANIEL_FORWARD_BEND_KNEE_MIN_ANGLE = 150.0

MARCH_MOTION_NAME = "\uc81c\uc790\ub9ac \uac77\uae30"
SIDE_STEP_MOTION_NAME = "\uc0ac\uc774\ub4dc \uc2a4\ud15d"
DIAGONAL_BODY_PUNCH_MOTION_NAME = "\ub300\uac01\uc120 \ubab8\ud1b5 \uc9c0\ub974\uae30"
DIAGONAL_FACE_PUNCH_MOTION_NAME = "\ub300\uac01\uc120 \uc5bc\uad74 \uc9c0\ub974\uae30"

DEFAULT_SIDE_STEP_TARGET_STEPS = 8
DEFAULT_SIDE_STEP_EXTENT_THRESHOLD = 0.35
DEFAULT_SIDE_STEP_ANKLE_SPAN_THRESHOLD = 0.45
DEFAULT_SIDE_STEP_DOMINANCE_MARGIN = 0.10
DEFAULT_SIDE_STEP_RELEASE_THRESHOLD = 0.12
DEFAULT_SIDE_STEP_TORSO_TILT_MAX = 12.0
DEFAULT_SIDE_STEP_DEPTH_SHIFT_MAX = 0.40

DEFAULT_DIAGONAL_BODY_PUNCH_TARGET_STEPS = 8
DEFAULT_DIAGONAL_BODY_PUNCH_FORWARD_THRESHOLD = 0.60
DEFAULT_DIAGONAL_BODY_PUNCH_STANCE_SPAN_THRESHOLD = 0.60
DEFAULT_DIAGONAL_BODY_PUNCH_DOMINANCE_MARGIN = 0.10
DEFAULT_DIAGONAL_BODY_PUNCH_RELEASE_THRESHOLD = 0.30
DEFAULT_DIAGONAL_BODY_PUNCH_ARM_STRAIGHT_THRESHOLD = 145.0
DEFAULT_DIAGONAL_BODY_PUNCH_GUARD_BEND_THRESHOLD = 125.0
DEFAULT_DIAGONAL_BODY_PUNCH_TORSO_TILT_MAX = 14.0
DEFAULT_DIAGONAL_BODY_PUNCH_DEPTH_SHIFT_MAX = 0.70

DEFAULT_DIAGONAL_FACE_PUNCH_TARGET_STEPS = 8
DEFAULT_DIAGONAL_FACE_PUNCH_FORWARD_THRESHOLD = 0.60
DEFAULT_DIAGONAL_FACE_PUNCH_HEIGHT_THRESHOLD = 0.08
DEFAULT_DIAGONAL_FACE_PUNCH_STANCE_SPAN_THRESHOLD = 0.60
DEFAULT_DIAGONAL_FACE_PUNCH_DOMINANCE_MARGIN = 0.10
DEFAULT_DIAGONAL_FACE_PUNCH_RELEASE_THRESHOLD = 0.30
DEFAULT_DIAGONAL_FACE_PUNCH_ARM_STRAIGHT_THRESHOLD = 145.0
DEFAULT_DIAGONAL_FACE_PUNCH_GUARD_BEND_THRESHOLD = 125.0
DEFAULT_DIAGONAL_FACE_PUNCH_TORSO_TILT_MAX = 14.0
DEFAULT_DIAGONAL_FACE_PUNCH_DEPTH_SHIFT_MAX = 0.70

DEFAULT_SQUAT_TARGET_STEPS = 8
DEFAULT_SQUAT_DESCEND_THRESHOLD = 0.08
DEFAULT_SQUAT_BOTTOM_THRESHOLD = 0.30
DEFAULT_SQUAT_RETURN_THRESHOLD = 0.03
DEFAULT_SQUAT_TORSO_TILT_MAX = 30.0
DEFAULT_SQUAT_LATERAL_SHIFT_MAX = 0.30

SQUAT_MOTION_NAME = "앉았다 일어서기"
